import { app } from 'electron'
import { mkdirSync, writeFileSync } from 'fs'
import { basename, join } from 'path'

/**
 * Inject an OSC 7 cwd-notification hook into the user's shell so the renderer
 * can keep PaneToolbar in sync with `cd` commands. Each PTY emits
 *
 *   \e]7;file://<host>/<cwd>\e\
 *
 * on every prompt; Terminal.vue's OSC 7 handler parses it and updates the
 * currentCwd ref.
 *
 * Strategy is shell-specific:
 *   bash       — `--rcfile` pointing to a tempfile that sources ~/.bashrc + adds PROMPT_COMMAND
 *   zsh        — set ZDOTDIR to a tempdir; its .zshrc sources the real one + adds precmd hook
 *   powershell — `-NoLogo -NoExit -Command` to install a custom `prompt` function
 *   pwsh       — same as powershell
 *   cmd.exe    — set PROMPT env var with `$E]7;file://...$E\` prefix
 *   other      — no integration (toolbar will only update on focus via ptyGetCwd)
 */
export interface ShellSpec {
  shell: string
  args: string[]
  env: Record<string, string | undefined>
}

function shellName(shellPath: string): string {
  return basename(shellPath)
    .toLowerCase()
    .replace(/\.(exe|cmd|bat)$/, '')
}

function integrationsDir(): string {
  const dir = join(app.getPath('home'), '.Gittim', 'integrations')
  mkdirSync(dir, { recursive: true })
  return dir
}

function writeBashRc(): string {
  const path = join(integrationsDir(), 'bash.rc')
  // Single-quoted printf format so $HOSTNAME/$PWD aren't expanded at script-parse
  // time; we pass them as printf args. \033 = ESC, \033\\ = OSC string terminator.
  const content =
    '# Auto-generated by Gittim. Sourced via --rcfile to enable OSC 7 cwd tracking.\n' +
    '[ -r ~/.bashrc ] && source ~/.bashrc\n' +
    '__gittim_osc7() {\n' +
    `  printf '\\033]7;file://%s%s\\033\\\\' "\${HOSTNAME:-localhost}" "$PWD"\n` +
    '}\n' +
    `PROMPT_COMMAND="__gittim_osc7\${PROMPT_COMMAND:+;$PROMPT_COMMAND}"\n`
  writeFileSync(path, content)
  return path
}

function writeZshDir(): string {
  const dir = join(integrationsDir(), 'zsh')
  mkdirSync(dir, { recursive: true })
  const content =
    '# Auto-generated by Gittim. Sourced via ZDOTDIR to enable OSC 7 cwd tracking.\n' +
    '# Restore the user\'s real ZDOTDIR (if any) before sourcing their .zshrc.\n' +
    'if [ -n "$ZDOTDIR_REAL" ]; then export ZDOTDIR="$ZDOTDIR_REAL"; else unset ZDOTDIR; fi\n' +
    '[ -r "${ZDOTDIR:-$HOME}/.zshrc" ] && source "${ZDOTDIR:-$HOME}/.zshrc"\n' +
    '__gittim_osc7() {\n' +
    `  printf '\\033]7;file://%s%s\\033\\\\' "\${HOST:-localhost}" "$PWD"\n` +
    '}\n' +
    'typeset -ag precmd_functions\n' +
    'precmd_functions+=(__gittim_osc7)\n'
  writeFileSync(join(dir, '.zshrc'), content)
  return dir
}

// PowerShell prompt function. Returns a string containing OSC 7 + the visible
// prompt; xterm.js strips the escape sequence before rendering. Use [char]27
// for ESC since '\e' isn't a PS escape and ANSI-quoted strings aren't universal.
function powershellCommand(): string {
  return [
    'function global:prompt {',
    '  $cwd = $ExecutionContext.SessionState.Path.CurrentLocation.Path',
    '  $host_ = if ($env:COMPUTERNAME) { $env:COMPUTERNAME } else { "localhost" }',
    '  $esc = [char]27',
    '  $osc = "$esc]7;file://$host_/$($cwd.Replace([char]92,[char]47))$esc\\"',
    '  "$osc" + "PS $cwd> "',
    '}'
  ].join('; ')
}

export function shellIntegration(shellPath: string): ShellSpec {
  const name = shellName(shellPath)
  const baseEnv: Record<string, string | undefined> = { ...process.env }

  if (name === 'bash') {
    const rc = writeBashRc()
    return { shell: shellPath, args: ['--rcfile', rc], env: baseEnv }
  }

  if (name === 'zsh') {
    const env = { ...baseEnv }
    if (env.ZDOTDIR) env.ZDOTDIR_REAL = env.ZDOTDIR
    env.ZDOTDIR = writeZshDir()
    return { shell: shellPath, args: [], env }
  }

  if (name === 'powershell' || name === 'pwsh') {
    return {
      shell: shellPath,
      args: ['-NoLogo', '-NoExit', '-Command', powershellCommand()],
      env: baseEnv
    }
  }

  if (name === 'cmd') {
    // $E = ESC, $P = current path, $G = '>'. We substitute %COMPUTERNAME%
    // ourselves rather than relying on cmd's lazy expansion semantics, which
    // differ between interactive `set` and inherited-env values.
    const env = { ...baseEnv }
    const host = env.COMPUTERNAME || 'localhost'
    env.PROMPT = `$E]7;file://${host}/$P$E\\$P$G`
    return { shell: shellPath, args: [], env }
  }

  // Unknown shell — let it run as-is. OSC 7 won't be emitted automatically,
  // but ptyGetCwd on focus still works on Linux/macOS.
  return { shell: shellPath, args: [], env: baseEnv }
}
